DATA_DIR = 'data'
OUTPUT_INTERACTIONFILENAME = 'data\output.interactions'
DB_PATH = 'C:\Users\TheatroIT\Documents\Scripts2\interactions_to_db\output_peewee_integration.sqlite'
DATA_SOURCE = 'csv'
#DATA_SOURCE = 'sqlite'
